### PR TITLE
[FIX] Toggle missing bar

### LINKED ISSUE #158: [BUG] hamburger menu is missing a bar
Screenshot 2022-05-23 at 9 58 55 AM

### Expected behaviour
Screenshot 2022-05-23 at 9 22 25 PM

@Sing-Li Any thought on this, it seems missing

### PR DESCRIPTION
**Pull request by Abusayid693**
This PR fixes #158 

### Please check this video demo

https://user-images.githubusercontent.com/35341198/169880185-ddb64a07-e722-4cc3-b70a-3a9d46517a52.mov

Screenshot 2022-05-23 at 10 51 23 PM

@Sing-Li can you please review this PR

### CODE REVIEW

File: app/components/menubar.js [hunk 1]
```diff
@@ -1,11 +1,11 @@
-import React, {useState } from 'react';
-import { Navbar, Nav, NavDropdown, Container, Dropdown } from 'react-bootstrap';
+import Cookies from 'js-cookie';
+import Link from 'next/link';
+import React, { useState } from 'react';
+import { Container, Dropdown, Nav, Navbar, NavDropdown } from 'react-bootstrap';
```
Comment (Sing-Li) [inline app/components/menubar.js:4]: Clean this up - you moved the headers around on all files.  Thanks.

**Review by Sing-Li — CHANGES_REQUESTED** [review]

File: app/components/menubar.js (hunk 1 above)
Comment (Abusayid693) [reply app/components/menubar.js]: Cleaned it, happened coz of vs-code automatic imports organise setting

**Comment by Sing-Li** [comment]
Thanks for the contribution @Abusayid693 - and welcome to the RC4Community community 🙂
